# Generated by Django 5.1.2 on 2024-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('russian', models.CharField(blank=True, max_length=200, null=True)),
                ('license_name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('english', models.CharField(blank=True, max_length=200, null=True)),
                ('japanese', models.CharField(blank=True, max_length=200, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('kind', models.CharField(max_length=50)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('episodes_aired', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('aired_on', models.DateField(blank=True, null=True)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('poster', models.JSONField(blank=True, null=True)),
                ('fansubbers', models.JSONField(blank=True, default=list)),
                ('fandubbers', models.JSONField(blank=True, default=list)),
                ('licensors', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
