# Generated by Django 5.1.2 on 2024-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.CharField(choices=[('none', 'None'), ('g', 'G'), ('pg', 'Pg'), ('pg_13', 'Pg 13'), ('r', 'R 17'), ('r_plus', 'R Plus'), ('rx', 'Rx')], max_length=10, null=True),
        ),
    ]
