# Generated by Django 5.1.2 on 2024-10-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='anime',
            name='isCensored',
            field=models.BooleanField(default=False),
        ),
    ]
