# Generated by Django 5.1.2 on 2024-10-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_anime_genres_anime_iscensored'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='character_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='descriptionHtml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='descriptionSource',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='person_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='anime',
            name='related',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='anime',
            name='scores_stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='anime',
            name='screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='anime',
            name='statusesStats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='anime',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
