# Generated by Django 5.1.2 on 2024-10-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_anime_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('anons', 'Planned'), ('ongoing', 'Airing'), ('released', 'Released')], max_length=10, null=True),
        ),
    ]
