# Generated by Django 5.1.2 on 2024-10-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_anime_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
