# Generated by Django 5.1.2 on 2024-10-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_anime_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='next_episode_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='external_links',
            field=models.ManyToManyField(blank=True, related_name='animes', to='api.externallink'),
        ),
    ]
