# Generated by Django 5.1.2 on 2024-10-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_anime_airedon_delete_airedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='airedOn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airedOn', to='api.incompletedata'),
        ),
        migrations.AddField(
            model_name='anime',
            name='releasedOn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releasedOn', to='api.incompletedata'),
        ),
    ]
