# Generated by Django 5.1.2 on 2024-10-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_anime_airedon_anime_releasedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main2xUrl', models.URLField(blank=True, null=True)),
                ('mainAlt2xUrl', models.URLField(blank=True, null=True)),
                ('mainAltUrl', models.URLField(blank=True, null=True)),
                ('mainUrl', models.URLField(blank=True, null=True)),
                ('mini2xUrl', models.URLField(blank=True, null=True)),
                ('miniAlt2xUrl', models.URLField(blank=True, null=True)),
                ('miniAltUrl', models.URLField(blank=True, null=True)),
                ('miniUrl', models.URLField(blank=True, null=True)),
                ('originalUrl', models.URLField(blank=True, null=True)),
                ('preview2xUrl', models.URLField(blank=True, null=True)),
                ('previewAlt2xUrl', models.URLField(blank=True, null=True)),
                ('previewAltUrl', models.URLField(blank=True, null=True)),
                ('previewUrl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='api.poster'),
        ),
    ]
