# Generated by Django 5.1.2 on 2024-10-30 19:42

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_anime_fandubbers_anime_fansubbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='isCensored',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='licensors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255, null=True), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='anime',
            name='nextEpisodeAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
