# Generated by Django 5.1.2 on 2024-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_anime_createdat_anime_iscensored_anime_licensors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='createdAt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='nextEpisodeAt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='updatedAt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
