# Generated by Django 5.1.2 on 2024-10-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_anime_createdat_alter_anime_nextepisodeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryType', models.CharField(blank=True, choices=[('Anime', 'Anime'), ('Mange', 'Manga')], max_length=5, null=True)),
                ('kind', models.CharField(blank=True, choices=[('demographic', 'Demographic'), ('genre', 'Genre'), ('theme', 'Theme')], max_length=12, null=True)),
                ('name', models.CharField(max_length=120)),
                ('russian', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='api.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='api.studio'),
        ),
    ]
