# Generated by Django 5.1.2 on 2024-10-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_anime_studios_remove_anime_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, default=list, related_name='genre', to='api.genre'),
        ),
    ]
