# Generated by Django 5.1.2 on 2024-10-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_anime_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, default=list, related_name='genre', to='api.studio'),
        ),
    ]
