# Generated by Django 5.1.2 on 2024-10-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_anime_characterroles_alter_anime_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
