# Generated by Django 5.1.2 on 2024-10-30 23:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_anime_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='characterRoles',
            field=models.ManyToManyField(blank=True, default=dict, to='api.characterrole'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodesAired',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='externalLinks',
            field=models.ManyToManyField(blank=True, default=dict, to='api.externallink'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='fandubbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='fansubbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, default=dict, to='api.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='licensors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, default=dict, to='api.studio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='isAnime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='isManga',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='isRanobe',
            field=models.BooleanField(default=False),
        ),
    ]
