# Generated by Django 5.1.2 on 2024-10-31 13:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_anime_characterroles_alter_anime_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isMangaka', models.BooleanField(default=False)),
                ('isProducer', models.BooleanField(default=False)),
                ('isSeyu', models.BooleanField(default=False)),
                ('japanese', models.TextField(blank=True, null=True)),
                ('malId', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('russian', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('birthOn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_birthOn', to='api.incompletedata')),
                ('deceasedOn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_decasedOn', to='api.incompletedata')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.poster')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolesEn', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('rulesRu', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='personRoles',
            field=models.ManyToManyField(blank=True, default=dict, to='api.personrole'),
        ),
    ]
