# Generated by Django 5.1.2 on 2024-10-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_person_personrole_anime_personroles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personrole',
            old_name='rulesRu',
            new_name='rolesRu',
        ),
    ]
