# Generated by Django 5.1.2 on 2024-10-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_rulesru_personrole_rolesru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationText', models.TextField(blank=True, null=True)),
                ('relationEn', models.CharField(blank=True, max_length=255, null=True)),
                ('manga', models.JSONField(blank=True, null=True)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_anime', to='api.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='related',
            field=models.ManyToManyField(blank=True, default=dict, related_name='anime_related', to='api.related'),
        ),
    ]
