# Generated by Django 5.1.2 on 2024-10-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_related_anime_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='related',
            name='relationKind',
            field=models.CharField(blank=True, choices=[('adaptation', 'Adaptation'), ('alternative_setting', 'Alternative Setting'), ('alternative_version', 'Alternative Version'), ('character', 'Character'), ('full_story', 'Full Story'), ('other', 'Other'), ('parent_story', 'Parent Story'), ('prequel', 'Prequel'), ('sequel', 'Sequel'), ('side_story', 'Side Story'), ('spin_off', 'Spin-off'), ('summary', 'Summary')], max_length=19, null=True),
        ),
    ]
