# Generated by Django 5.1.2 on 2024-10-31 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_manga_remove_related_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='related',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_manga', to='api.manga'),
        ),
    ]
