# Generated by Django 5.1.2 on 2024-10-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_related_manga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, choices=[('pv', 'PV'), ('character_trailer', 'Character trailer'), ('cm', 'CM'), ('op', 'OP'), ('ed', 'ED'), ('op_ed_clip', 'Music'), ('clip', 'Clip'), ('other', 'Other'), ('episode_preview', 'Episode preview')], max_length=20, null=True)),
                ('name', models.CharField(max_length=120)),
                ('playerUrl', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='videos',
            field=models.ManyToManyField(blank=True, default=dict, to='api.video'),
        ),
    ]
