# Generated by Django 5.1.2 on 2024-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_video_anime_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoresStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalUrl', models.URLField(blank=True, null=True)),
                ('x166Url', models.URLField(blank=True, null=True)),
                ('x332Url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusesStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('planned', 'Planned to Watch'), ('watching', 'Watching'), ('rewatching', 'Rewatching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='scoreStats',
            field=models.ManyToManyField(blank=True, default=dict, to='api.scoresstat'),
        ),
        migrations.AddField(
            model_name='anime',
            name='screenshots',
            field=models.ManyToManyField(blank=True, default=dict, to='api.screenshot'),
        ),
        migrations.AddField(
            model_name='anime',
            name='statusesStats',
            field=models.ManyToManyField(blank=True, default=dict, to='api.statusesstat'),
        ),
    ]
