# Generated by Django 5.1.2 on 2024-10-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_scoresstat_screenshot_statusesstat_anime_scorestats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='scoreStats',
            new_name='scoresStats',
        ),
    ]
