# Generated by Django 5.1.2 on 2024-11-02 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_anime_createdat_remove_anime_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
