# Generated by Django 5.1.2 on 2024-11-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_anime_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
