# Generated by Django 5.1.2 on 2024-11-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_anime_updatedat_alter_anime_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='malId',
            field=models.IntegerField(null=True),
        ),
    ]
