# Generated by Django 5.1.2 on 2024-11-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_anime_createdat_alter_anime_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incompletedata',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incompletedata',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incompletedata',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
